### ISSUE TITLE
igmCppPort.dll issue

### ISSUE THREAD

**Issue by hjforsythe-rlp** [xarthurx/IG-Mesh#2]
**Describe the bug**

unable to use IGmesh components downloaded from package manager because of this error:
1. Solution exception:igmCppPort.dll assembly:<unknown assembly> type:<unknown type> member:(null)

Tried on both Windows and Mac M1 devices with the same error.

**To Reproduce**
Using the Examples file provided, all components were throwing this error.

steps taken so far:

unblocked all components (.dll and gha)
downloaded from food4rhino and package manager
tried with files in package folder and components folder on both dell and mac

**Expected behavior**
working?

**Screenshots and Grasshopper links (if possible)**

none

**Comment by hjforsythe-rlp** [comment]
Windows Error Update: 

Assertion Failed!
Program ... \packages\7.0\IG-Mesh\0.2.7\igmCppPort.dll
File: C:\Libraries\vcpkg\installed\x64-...\DenseCo...sBase.h
Line 427

Expression: index >=0 && index < size()
 
This is thrown when a new mesh in input into a component such as igGeoDist

**Comment by xarthurx** [comment]
> Windows Error Update: 
> 
> 
> 
> Assertion Failed!
> 
> Program ... \packages\7.0\IG-Mesh\0.2.7\igmCppPort.dll
> 
> File: C:\Libraries\vcpkg\installed\x64-...\DenseCo...sBase.h
> 
> Line 427
> 
> 
> 
> Expression: index >=0 && index < size()
> 
>  
> 
> This is thrown when a new mesh in input into a component such as igGeoDist

Hello, thanks for the report.
From the error message, it seems the problem is caused by the quality of the mesh, which causes matrix computation fail.

Is your mesh a triangle-based mesh? 
Could you try using "triangulate" component from GH to first triangulate the mesh and then try the 'geodist' component?

If the problem still exists, could you provide a link to download the mesh?


I'm currently on vacation now, and don't have access to the compiling env. But will be back around Jun 11.

**Comment by xarthurx** [comment]
Another possibility is the .dll file is compiled for x64 system only.

If your windows is x86, the lib might not work. And I don't have Apple M1, which I cannot support yet.

**Comment by hjforsythe-rlp** [comment]
Just Tried: Mesh Sphere and Cylinder Gh Components ---> Triangulate Gh component  ---> igGeodesic

Windows still returns the same error on these triangulated meshes

I have attached the meshes to this file as well as a screenshot of the error. 

[IgMesh_Error_Meshes.gh.zip](https://github.com/xarthurx/IG-Mesh/files/8824991/IgMesh_Error_Meshes.gh.zip)

no rush on this issue. Enjoy your vacation :)

PS. The error on my Mac is still different than Windows
 (Mac Error: Solution exception:igmCppPort.dll assembly: type: member:(null) )

**Comment by hjforsythe-rlp** [comment]
> Another possibility is the .dll file is compiled for x64 system only.
> 
> If your windows is x86, the lib might not work. And I don't have Apple M1, which I cannot support yet.

Currently using windows x64, and yeah not many RH/GH tools support M1 yet which is too bad :/

**Comment by xarthurx** [comment]
> Just Tried: Mesh Sphere and Cylinder Gh Components ---> Triangulate Gh component ---> igGeodesic
> 
> Windows still returns the same error on these triangulated meshes
> 
> I have attached the meshes to this file as well as a screenshot of the error.
> 
> [IgMesh_Error_Meshes.gh.zip](https://github.com/xarthurx/IG-Mesh/files/8824991/IgMesh_Error_Meshes.gh.zip)
> 
> no rush on this issue. Enjoy your vacation :)
> 
> PS. The error on my Mac is still different than Windows (Mac Error: Solution exception:igmCppPort.dll assembly: type: member:(null) )

Hi, I'm back and try to figure out what happened to your IG-Mesh.

![image](https://user-images.githubusercontent.com/1921878/173294138-cb2614b5-a88e-4243-93a0-bd49bbffeefc.png)
Here is what happened to me following your steps. 
Clearly, it is not what happened to you...

To clarify, are you using Windows x64 on a MacBook or on normal non-mac computer?

**Comment by xarthurx** [comment]
I'm closing this issue due to a lack of activity.
If you have questions, you can re-open it again.

**Comment by xarthurx** [comment]
OK.

Then I need to check it once I get back and have access to my development computer.

Will update later.
